[package]
name = "split360"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
capstone = "0.11.0"
sha1 = "0.10.5"
hex = "0.4.3"
regex = "1.11.1"
